seed: 0

input:
  image_size: 384

transform:
  rotation: 180.
  shear: 2.
  height_zoom: 8.
  width_zoom: 8.
  height_shift: 8.
  width_shift: 8.

lr_scheduling:
  lr_start: 1e-6
  lr_max: 1.25e-7
  lr_min: 1e-7
  lr_ramp_ep: 5
  lr_sus_ep: 0
  lr_decay: 0.8

validation:
  n_folds: 5

modeling:
  batch_size: 32
  epochs: 12

post_processing:
  tta_rounds: 11
